name: CI/CD WebSocket Deployment

on:
  push:
    branches:
      - main # Or the branch you deploy from, e.g., 'develop'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/websocket:latest # Specific tag for your WebSocket service
        context: .
        file: ./Dockerfile # Assuming Dockerfile is in the root of this repo
  
    - name: Deploy WebSocket to DigitalOcean Droplet
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.DO_SSH_HOST }}
        username: ${{ secrets.DO_SSH_USER }}
        key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        script: |
          # Pull the latest Docker image for your WebSocket service
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/websocket:latest
          
          # Stop and remove any existing container named 'websocket'
          docker stop websocket || true
          docker rm websocket || true
          
          # Run the new WebSocket container, mapping port 3000
          docker run -d --name websocket -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/websocket:latest
          
          echo "WebSocket deployment completed!"
